name: REST Automation (Postman)
on:
  push:
    branches: [ main ]
jobs:
  test-rest-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install Newman
      run: npm install -g newman
    - name: Run Postman Tests
      run: |
        newman run Postman/Booker-API-Collection.json         -e Postman/Booker-Environment.json         --reporters cli
